In [1]:
import torch

In [43]:
x = torch.randn((3, 4))
y = torch.randn((3, 4))
print("x:{}  \ny:{}".format(x.size(), y.size()))
z0 = torch.cat((x, y), dim=0)
print(z0.size())
z1 = torch.cat((x, y), dim=1)
z1.size()

x:torch.Size([3, 4])  
y:torch.Size([3, 4])
torch.Size([6, 4])


torch.Size([3, 8])

In [36]:
import einops
from functools import partial

In [4]:
cp = torch.cumprod(x, axis=0)
cp

tensor([  1,   2,   6,  24, 120, 720])

In [3]:
init_dim = 32
ImageSize = 128
dim_mults=[1, 2, 4, 8]

dims = [init_dim, *map(lambda m: ImageSize * m, dim_mults)]
in_out = list(zip(dims[:-1], dims[1:]))

In [4]:
in_out

[(32, 128), (128, 256), (256, 512), (512, 1024)]

In [5]:
dims

[32, 128, 256, 512, 1024]

In [10]:
new_list = [ImageSize * m for m in dim_mults]
new_list

[128, 256, 512, 1024]

In [12]:
y = [2, *new_list]

In [13]:
y

[2, 128, 256, 512, 1024]

In [14]:
newdims = [init_dim, *(ImageSize * m for m in dim_mults)]

In [15]:
newdims

[32, 128, 256, 512, 1024]

In [16]:
newdims[:-1], newdims[1:]

([32, 128, 256, 512], [128, 256, 512, 1024])

In [28]:
weight = torch.tensor([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
])
weight.size()

torch.Size([2, 3, 3])

In [32]:
mean = einops.reduce(weight.float(), "x ... -> x 1 1 1", "mean")
mean, mean.size()

(tensor([[[[ 5.]]],
 
 
         [[[14.]]]]),
 torch.Size([2, 1, 1, 1]))

In [33]:
nx = weight - mean
nx

tensor([[[[ -4.,  -3.,  -2.],
          [ -1.,   0.,   1.],
          [  2.,   3.,   4.]],

         [[  5.,   6.,   7.],
          [  8.,   9.,  10.],
          [ 11.,  12.,  13.]]],


        [[[-13., -12., -11.],
          [-10.,  -9.,  -8.],
          [ -7.,  -6.,  -5.]],

         [[ -4.,  -3.,  -2.],
          [ -1.,   0.,   1.],
          [  2.,   3.,   4.]]]])

In [38]:
var = einops.reduce(weight.float(), "o ... -> o 1 1 1", partial(torch.var, unbiased=False))
var

tensor([[[[6.6667]]],


        [[[6.6667]]]])

In [34]:
x = torch.ones((2, 2, 3, 4))
y = torch.ones((2, 2)) * 2
x, y

(tensor([[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],
 
          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],
 
 
         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],
 
          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]]]),
 tensor([[2., 2.],
         [2., 2.]]))

In [19]:
z = torch.ones((2, 2, 3, 4)) * 3
z

tensor([[[[3., 3., 3., 3.],
          [3., 3., 3., 3.],
          [3., 3., 3., 3.]],

         [[3., 3., 3., 3.],
          [3., 3., 3., 3.],
          [3., 3., 3., 3.]]],


        [[[3., 3., 3., 3.],
          [3., 3., 3., 3.],
          [3., 3., 3., 3.]],

         [[3., 3., 3., 3.],
          [3., 3., 3., 3.],
          [3., 3., 3., 3.]]]])

In [8]:
x + z

tensor([[[[4., 4., 4., 4.],
          [4., 4., 4., 4.],
          [4., 4., 4., 4.]],

         [[4., 4., 4., 4.],
          [4., 4., 4., 4.],
          [4., 4., 4., 4.]]],


        [[[4., 4., 4., 4.],
          [4., 4., 4., 4.],
          [4., 4., 4., 4.]],

         [[4., 4., 4., 4.],
          [4., 4., 4., 4.],
          [4., 4., 4., 4.]]]])

In [21]:
c0 = torch.cat((x, z), dim=0)
c0.shape,c0

(torch.Size([4, 2, 3, 4]),
 tensor([[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],
 
          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],
 
 
         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],
 
          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]],
 
 
         [[[3., 3., 3., 3.],
           [3., 3., 3., 3.],
           [3., 3., 3., 3.]],
 
          [[3., 3., 3., 3.],
           [3., 3., 3., 3.],
           [3., 3., 3., 3.]]],
 
 
         [[[3., 3., 3., 3.],
           [3., 3., 3., 3.],
           [3., 3., 3., 3.]],
 
          [[3., 3., 3., 3.],
           [3., 3., 3., 3.],
           [3., 3., 3., 3.]]]]))

In [22]:
c1 = torch.cat((x, z), dim=1)
c1.shape, c1

(torch.Size([2, 4, 3, 4]),
 tensor([[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],
 
          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],
 
          [[3., 3., 3., 3.],
           [3., 3., 3., 3.],
           [3., 3., 3., 3.]],
 
          [[3., 3., 3., 3.],
           [3., 3., 3., 3.],
           [3., 3., 3., 3.]]],
 
 
         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],
 
          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],
 
          [[3., 3., 3., 3.],
           [3., 3., 3., 3.],
           [3., 3., 3., 3.]],
 
          [[3., 3., 3., 3.],
           [3., 3., 3., 3.],
           [3., 3., 3., 3.]]]]))

In [23]:
c3 = torch.cat((x, z), dim=2)
c3.shape, c3

(torch.Size([2, 2, 6, 4]),
 tensor([[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [3., 3., 3., 3.],
           [3., 3., 3., 3.],
           [3., 3., 3., 3.]],
 
          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [3., 3., 3., 3.],
           [3., 3., 3., 3.],
           [3., 3., 3., 3.]]],
 
 
         [[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [3., 3., 3., 3.],
           [3., 3., 3., 3.],
           [3., 3., 3., 3.]],
 
          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [3., 3., 3., 3.],
           [3., 3., 3., 3.],
           [3., 3., 3., 3.]]]]))

In [25]:
c4 = torch.cat((x, z), dim=3)
c4.shape,c4

(torch.Size([2, 2, 3, 8]),
 tensor([[[[1., 1., 1., 1., 3., 3., 3., 3.],
           [1., 1., 1., 1., 3., 3., 3., 3.],
           [1., 1., 1., 1., 3., 3., 3., 3.]],
 
          [[1., 1., 1., 1., 3., 3., 3., 3.],
           [1., 1., 1., 1., 3., 3., 3., 3.],
           [1., 1., 1., 1., 3., 3., 3., 3.]]],
 
 
         [[[1., 1., 1., 1., 3., 3., 3., 3.],
           [1., 1., 1., 1., 3., 3., 3., 3.],
           [1., 1., 1., 1., 3., 3., 3., 3.]],
 
          [[1., 1., 1., 1., 3., 3., 3., 3.],
           [1., 1., 1., 1., 3., 3., 3., 3.],
           [1., 1., 1., 1., 3., 3., 3., 3.]]]]))

In [41]:
y0 = y.unsqueeze(2).unsqueeze(3)
y0.size(), y0

(torch.Size([2, 2, 1, 1]),
 tensor([[[[2.]],
 
          [[2.]]],
 
 
         [[[2.]],
 
          [[2.]]]]))

In [42]:
y1 = y0.expand(x.shape)
y1.shape, y1

(torch.Size([2, 2, 3, 4]),
 tensor([[[[2., 2., 2., 2.],
           [2., 2., 2., 2.],
           [2., 2., 2., 2.]],
 
          [[2., 2., 2., 2.],
           [2., 2., 2., 2.],
           [2., 2., 2., 2.]]],
 
 
         [[[2., 2., 2., 2.],
           [2., 2., 2., 2.],
           [2., 2., 2., 2.]],
 
          [[2., 2., 2., 2.],
           [2., 2., 2., 2.],
           [2., 2., 2., 2.]]]]))