In [2]:
import torch

x = torch.randn(3,4,5)
x

tensor([[[ 0.3257,  0.4166,  0.3198, -0.4368,  1.9397],
         [ 0.1774, -1.2168, -0.0464, -0.6074,  0.3345],
         [ 0.4140, -0.3924, -0.3448, -2.2866, -0.0033],
         [ 0.6049, -1.4979,  0.2806, -0.9642,  0.8085]],

        [[-0.3944, -0.5186,  0.5707, -0.9030,  0.1591],
         [ 1.8268, -1.3314,  0.2680,  1.0187, -1.0157],
         [ 0.7353,  0.6496, -1.0346,  0.7247, -0.7260],
         [ 1.7558, -0.7640, -0.1694,  0.3263,  1.3588]],

        [[ 0.3160,  0.4531, -1.6166, -0.4806,  1.4292],
         [-0.8991, -2.0487,  1.4671,  0.4362,  0.8358],
         [ 1.0464, -0.9916, -1.3631,  1.2615,  1.0947],
         [ 1.2853,  0.4307,  1.4011,  0.1219, -0.2761]]])

In [3]:
#先split or chunk, 再transport
q,p = x.split(2, 1)
q = q.transpose(1, 2)
p = p.transpose(1, 2)
q, p

(tensor([[[ 0.3257,  0.1774],
          [ 0.4166, -1.2168],
          [ 0.3198, -0.0464],
          [-0.4368, -0.6074],
          [ 1.9397,  0.3345]],
 
         [[-0.3944,  1.8268],
          [-0.5186, -1.3314],
          [ 0.5707,  0.2680],
          [-0.9030,  1.0187],
          [ 0.1591, -1.0157]],
 
         [[ 0.3160, -0.8991],
          [ 0.4531, -2.0487],
          [-1.6166,  1.4671],
          [-0.4806,  0.4362],
          [ 1.4292,  0.8358]]]),
 tensor([[[ 0.4140,  0.6049],
          [-0.3924, -1.4979],
          [-0.3448,  0.2806],
          [-2.2866, -0.9642],
          [-0.0033,  0.8085]],
 
         [[ 0.7353,  1.7558],
          [ 0.6496, -0.7640],
          [-1.0346, -0.1694],
          [ 0.7247,  0.3263],
          [-0.7260,  1.3588]],
 
         [[ 1.0464,  1.2853],
          [-0.9916,  0.4307],
          [-1.3631,  1.4011],
          [ 1.2615,  0.1219],
          [ 1.0947, -0.2761]]]))

In [11]:
#先transport, 再split or chunk
print("(3,4,5)->(3,5,4)->(3,5,2)")
i, j = x.transpose(1, 2).chunk(3, 2)
i,j

(tensor([[[ 0.3257,  0.1774],
          [ 0.4166, -1.2168],
          [ 0.3198, -0.0464],
          [-0.4368, -0.6074],
          [ 1.9397,  0.3345]],
 
         [[-0.3944,  1.8268],
          [-0.5186, -1.3314],
          [ 0.5707,  0.2680],
          [-0.9030,  1.0187],
          [ 0.1591, -1.0157]],
 
         [[ 0.3160, -0.8991],
          [ 0.4531, -2.0487],
          [-1.6166,  1.4671],
          [-0.4806,  0.4362],
          [ 1.4292,  0.8358]]]),
 tensor([[[ 0.4140,  0.6049],
          [-0.3924, -1.4979],
          [-0.3448,  0.2806],
          [-2.2866, -0.9642],
          [-0.0033,  0.8085]],
 
         [[ 0.7353,  1.7558],
          [ 0.6496, -0.7640],
          [-1.0346, -0.1694],
          [ 0.7247,  0.3263],
          [-0.7260,  1.3588]],
 
         [[ 1.0464,  1.2853],
          [-0.9916,  0.4307],
          [-1.3631,  1.4011],
          [ 1.2615,  0.1219],
          [ 1.0947, -0.2761]]]),
 True,
 True)

In [16]:
#先split or chunk, 再transport : q, p
#先transport, 再split or chunk : i, j
#答案都是一样的
#但是不连续了.再transport前view
t1= torch.allclose(i, q)
t2 = torch.allclose(j, p)

c1 = i.is_contiguous()
c2 = q.is_contiguous()

t1, t2, c1, c2

(True, True, False, False)