In [1]:
import torch

x = torch.randn(3,4,5)
x

tensor([[[-2.2209,  0.9150,  0.0870, -2.3863, -1.4002],
         [-0.2238, -0.3708, -2.0351, -1.3360, -0.5971],
         [ 0.4368,  1.4396, -1.6051,  0.0761, -2.2430],
         [ 0.4615, -0.1677, -0.6475, -1.0015, -0.2180]],

        [[ 1.1572, -1.0068,  2.1139, -0.0373,  0.7883],
         [ 0.1780,  0.6052,  0.9080,  0.1725, -2.7521],
         [ 0.6409, -0.6183, -0.9580,  1.0580,  1.6752],
         [ 0.9612, -0.1192, -0.4618,  0.5756,  0.3785]],

        [[-0.8170, -0.1676, -0.4920,  0.0927, -2.2775],
         [ 0.4247,  0.5924,  0.9737, -1.0522, -1.4963],
         [-0.1280, -0.6747,  0.9780, -1.1540, -0.4913],
         [ 0.8206, -0.7445, -0.3022, -0.0460, -1.5865]]])

In [3]:
#先split or chunk, 再transport
q,p = x.split(2, 1)
q = q.transpose(1, 2)
p = p.transpose(1, 2)
q, p

(tensor([[[ 0.3257,  0.1774],
          [ 0.4166, -1.2168],
          [ 0.3198, -0.0464],
          [-0.4368, -0.6074],
          [ 1.9397,  0.3345]],
 
         [[-0.3944,  1.8268],
          [-0.5186, -1.3314],
          [ 0.5707,  0.2680],
          [-0.9030,  1.0187],
          [ 0.1591, -1.0157]],
 
         [[ 0.3160, -0.8991],
          [ 0.4531, -2.0487],
          [-1.6166,  1.4671],
          [-0.4806,  0.4362],
          [ 1.4292,  0.8358]]]),
 tensor([[[ 0.4140,  0.6049],
          [-0.3924, -1.4979],
          [-0.3448,  0.2806],
          [-2.2866, -0.9642],
          [-0.0033,  0.8085]],
 
         [[ 0.7353,  1.7558],
          [ 0.6496, -0.7640],
          [-1.0346, -0.1694],
          [ 0.7247,  0.3263],
          [-0.7260,  1.3588]],
 
         [[ 1.0464,  1.2853],
          [-0.9916,  0.4307],
          [-1.3631,  1.4011],
          [ 1.2615,  0.1219],
          [ 1.0947, -0.2761]]]))

In [11]:
#先transport, 再split or chunk
print("(3,4,5)->(3,5,4)->(3,5,2)")
i, j = x.transpose(1, 2).chunk(3, 2)
i,j

(tensor([[[ 0.3257,  0.1774],
          [ 0.4166, -1.2168],
          [ 0.3198, -0.0464],
          [-0.4368, -0.6074],
          [ 1.9397,  0.3345]],
 
         [[-0.3944,  1.8268],
          [-0.5186, -1.3314],
          [ 0.5707,  0.2680],
          [-0.9030,  1.0187],
          [ 0.1591, -1.0157]],
 
         [[ 0.3160, -0.8991],
          [ 0.4531, -2.0487],
          [-1.6166,  1.4671],
          [-0.4806,  0.4362],
          [ 1.4292,  0.8358]]]),
 tensor([[[ 0.4140,  0.6049],
          [-0.3924, -1.4979],
          [-0.3448,  0.2806],
          [-2.2866, -0.9642],
          [-0.0033,  0.8085]],
 
         [[ 0.7353,  1.7558],
          [ 0.6496, -0.7640],
          [-1.0346, -0.1694],
          [ 0.7247,  0.3263],
          [-0.7260,  1.3588]],
 
         [[ 1.0464,  1.2853],
          [-0.9916,  0.4307],
          [-1.3631,  1.4011],
          [ 1.2615,  0.1219],
          [ 1.0947, -0.2761]]]),
 True,
 True)

In [16]:
#先split or chunk, 再transport : q, p
#先transport, 再split or chunk : i, j
#答案都是一样的
#但是不连续了.再transport前view
t1= torch.allclose(i, q)
t2 = torch.allclose(j, p)

c1 = i.is_contiguous()
c2 = q.is_contiguous()

t1, t2, c1, c2

(True, True, False, False)

In [2]:
x = torch.randn(3,4,5)

In [3]:
print(x)

tensor([[[-2.2878e-01,  3.6689e-01,  5.3427e-01,  8.2137e-01,  7.3907e-01],
         [ 3.3671e-01, -5.8381e-01, -1.0123e+00, -2.4320e-01, -3.6292e-01],
         [ 1.3893e+00, -1.3449e+00, -8.8119e-02,  6.4827e-01, -8.0323e-01],
         [-3.4065e-01, -7.1189e-01,  1.4884e-01,  1.0788e+00,  7.3027e-01]],

        [[-8.2296e-01,  1.4358e+00, -9.0874e-01, -1.3011e-01, -1.7783e+00],
         [ 6.9172e-01,  1.2776e+00, -7.8644e-01,  1.0212e+00,  4.0324e-01],
         [-2.1293e+00, -5.7741e-01, -1.1442e+00,  9.4692e-01, -1.7378e+00],
         [ 1.3357e+00,  1.7039e+00,  4.1743e-01,  3.4863e-01, -6.1009e-01]],

        [[-2.1727e+00, -3.5979e-01,  5.6001e-04, -3.6029e-01,  7.3889e-01],
         [-4.8556e-01, -1.1420e-01, -1.6857e-01, -1.5829e+00, -6.3946e-02],
         [-1.3727e-01, -1.7110e+00,  2.2690e-02, -1.1913e-01,  8.6144e-01],
         [ 8.0983e-01, -3.2492e-01,  4.7587e-01,  1.2831e-01, -5.5445e-01]]])


In [4]:
torch.amax(x, 1)

tensor([[ 1.3893,  0.3669,  0.5343,  1.0788,  0.7391],
        [ 1.3357,  1.7039,  0.4174,  1.0212,  0.4032],
        [ 0.8098, -0.1142,  0.4759,  0.1283,  0.8614]])

In [5]:
torch.amax(x, 0)

tensor([[-0.2288,  1.4358,  0.5343,  0.8214,  0.7391],
        [ 0.6917,  1.2776, -0.1686,  1.0212,  0.4032],
        [ 1.3893, -0.5774,  0.0227,  0.9469,  0.8614],
        [ 1.3357,  1.7039,  0.4759,  1.0788,  0.7303]])

In [6]:
torch.amax(x, 2)

tensor([[ 0.8214,  0.3367,  1.3893,  1.0788],
        [ 1.4358,  1.2776,  0.9469,  1.7039],
        [ 0.7389, -0.0639,  0.8614,  0.8098]])

In [7]:
# 创建一个 3x4x5 的张量
tensor = torch.zeros(3, 4, 5)

# 使用 PyTorch 的 arange 函数生成从 0 到 59 的序列
sequence = torch.arange(60)

# 将序列重塑为 3x4x5 的形状
sequence = sequence.reshape((3, 4, 5))

# 将张量的值设置为序列的值
tensor[:] = sequence[:]

In [8]:
print(tensor)

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]],

        [[20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34.],
         [35., 36., 37., 38., 39.]],

        [[40., 41., 42., 43., 44.],
         [45., 46., 47., 48., 49.],
         [50., 51., 52., 53., 54.],
         [55., 56., 57., 58., 59.]]])


In [10]:
torch.amax(tensor, 0)

tensor([[40., 41., 42., 43., 44.],
        [45., 46., 47., 48., 49.],
        [50., 51., 52., 53., 54.],
        [55., 56., 57., 58., 59.]])

In [12]:
torch.amax(tensor, 1)

tensor([[15., 16., 17., 18., 19.],
        [35., 36., 37., 38., 39.],
        [55., 56., 57., 58., 59.]])

In [13]:
torch.amax(tensor, 2)

tensor([[ 4.,  9., 14., 19.],
        [24., 29., 34., 39.],
        [44., 49., 54., 59.]])