In [1]:
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset

In [2]:
import torch

# 创建一个包含0到59的列表
values = list(range(60))

# 生成一个长度为60的随机排列索引序列
random_indices = torch.randperm(60)

# 将序列重塑为 3x4x5 的形状
random_indices = random_indices.reshape((3, 4, 5))

# 创建一个形状为3x4x5的张量
tensor = torch.zeros(3, 4, 5)

# 使用随机索引填充张量的元素
for i in range(3):
    for j in range(4):
        for k in range(5):
            index = random_indices[i, j, k]
            value = values[index]
            tensor[i, j, k] = value

# 打印张量
print(tensor)

tensor([[[ 6., 51., 52., 45., 38.],
         [30.,  7., 40., 35., 41.],
         [ 5., 31., 47., 53., 20.],
         [21., 59., 16., 34., 19.]],

        [[32., 48., 54., 14., 49.],
         [37., 43., 18., 10., 58.],
         [ 3., 26., 22., 55.,  4.],
         [ 8., 17., 28., 57., 12.]],

        [[36., 23., 42.,  0., 56.],
         [33.,  9., 44., 39., 11.],
         [29., 13., 46., 24.,  2.],
         [50.,  1., 27., 15., 25.]]])


In [9]:
tensor[:, 0], tensor[:, 1], tensor[:, 2]

(tensor([[ 6., 51., 52., 45., 38.],
         [32., 48., 54., 14., 49.],
         [36., 23., 42.,  0., 56.]]),
 tensor([[30.,  7., 40., 35., 41.],
         [37., 43., 18., 10., 58.],
         [33.,  9., 44., 39., 11.]]),
 tensor([[ 5., 31., 47., 53., 20.],
         [ 3., 26., 22., 55.,  4.],
         [29., 13., 46., 24.,  2.]]))

In [14]:
tensor[0, :, :], tensor[1, :, :], tensor[2, :, :]

(tensor([[ 6., 51., 52., 45., 38.],
         [30.,  7., 40., 35., 41.],
         [ 5., 31., 47., 53., 20.],
         [21., 59., 16., 34., 19.]]),
 tensor([[32., 48., 54., 14., 49.],
         [37., 43., 18., 10., 58.],
         [ 3., 26., 22., 55.,  4.],
         [ 8., 17., 28., 57., 12.]]),
 tensor([[36., 23., 42.,  0., 56.],
         [33.,  9., 44., 39., 11.],
         [29., 13., 46., 24.,  2.],
         [50.,  1., 27., 15., 25.]]))

In [15]:
tensor[:, 0, :], tensor[:, 1, :], tensor[:, 2, :]

(tensor([[ 6., 51., 52., 45., 38.],
         [32., 48., 54., 14., 49.],
         [36., 23., 42.,  0., 56.]]),
 tensor([[30.,  7., 40., 35., 41.],
         [37., 43., 18., 10., 58.],
         [33.,  9., 44., 39., 11.]]),
 tensor([[ 5., 31., 47., 53., 20.],
         [ 3., 26., 22., 55.,  4.],
         [29., 13., 46., 24.,  2.]]))

In [3]:
torch.amax(tensor, 0)

tensor([[36., 51., 54., 45., 56.],
        [37., 43., 44., 39., 58.],
        [29., 31., 47., 55., 20.],
        [50., 59., 28., 57., 25.]])

In [4]:
torch.amax(tensor, 1)

tensor([[30., 59., 52., 53., 41.],
        [37., 48., 54., 57., 58.],
        [50., 23., 46., 39., 56.]])

In [5]:
torch.amax(tensor, 2)

tensor([[52., 41., 53., 59.],
        [54., 58., 55., 57.],
        [56., 44., 46., 50.]])