In [1]:
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset

In [2]:
x = torch.randn(10, 3)
x

tensor([[-2.0112, -0.5023, -1.0266],
        [-0.3935,  0.3393, -1.8887],
        [ 0.6576,  1.0174, -0.2056],
        [ 1.7138,  0.5081,  0.4498],
        [-0.7055,  0.9932, -1.0480],
        [-0.3653, -1.5944, -0.7431],
        [-0.5481,  0.8196,  1.3407],
        [ 0.6133,  1.1686, -0.0226],
        [ 0.1247, -1.4288,  0.9346],
        [ 0.7115, -1.1939,  0.5783]])

In [3]:
x.size()

torch.Size([10, 3])

In [4]:
x[0]

tensor([-2.0112, -0.5023, -1.0266])

In [5]:
x[0].size()

torch.Size([3])

In [6]:
a = torch.FloatTensor(1).uniform_(0, 2**32)
b = torch.FloatTensor(1).uniform_(0, 2**32)
a, b

(tensor([2.7132e+09]), tensor([2.8212e+09]))

In [7]:
# 原始的分类变量
categories = ['红色', '蓝色', '绿色', '红色', '绿色']

# 创建一个张量表示分类变量
tensor = torch.tensor([categories.index(category) for category in categories])

# 进行One-hot编码
one_hot = torch.nn.functional.one_hot(tensor)

print(tensor)
print(one_hot)

tensor([0, 1, 2, 0, 2])
tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [1, 0, 0],
        [0, 0, 1]])


In [9]:
c = [categories.index(category) for category in categories]
c

[0, 1, 2, 0, 2]

AttributeError: 'list' object has no attribute 'indexs'