In [1]:
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset

In [2]:
# 创建一个 3x4x5 的张量
tensor = torch.zeros(3, 4, 5)

# 生成一个长度为60的随机排列索引序列
random_indices = torch.randperm(60)

# 将序列重塑为 3x4x5 的形状
random_indices = random_indices.reshape((3, 4, 5))

# 根据随机索引重新排列张量的元素
tensor = tensor.flatten()[random_indices.flatten()].reshape((3, 4, 5))

# 打印张量
print(tensor)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


In [3]:
import torch

# 创建一个包含0到59的列表
values = list(range(60))

# 生成一个长度为60的随机排列索引序列
random_indices = torch.randperm(60)

# 将序列重塑为 3x4x5 的形状
random_indices = random_indices.reshape((3, 4, 5))

# 创建一个形状为3x4x5的张量
tensor = torch.zeros(3, 4, 5)

# 使用随机索引填充张量的元素
for i in range(3):
    for j in range(4):
        for k in range(5):
            index = random_indices[i, j, k]
            value = values[index]
            tensor[i, j, k] = value

# 打印张量
print(tensor)

tensor([[[56., 45., 27., 26.,  4.],
         [18., 40., 17.,  8., 42.],
         [19., 44., 31., 22., 24.],
         [34., 53.,  1., 30., 36.]],

        [[58., 37., 14., 51., 13.],
         [35., 20., 52., 46., 23.],
         [ 9.,  7., 39., 12.,  0.],
         [ 5., 43., 33., 59., 28.]],

        [[15., 54., 25.,  2., 21.],
         [48., 32., 38., 16., 50.],
         [47., 11., 10., 55., 29.],
         [41.,  3., 49., 57.,  6.]]])


In [5]:
torch.amax(tensor, 0)

tensor([[58., 54., 27., 51., 21.],
        [48., 40., 52., 46., 50.],
        [47., 44., 39., 55., 29.],
        [41., 53., 49., 59., 36.]])

In [6]:
torch.amax(tensor, 1)

tensor([[56., 53., 31., 30., 42.],
        [58., 43., 52., 59., 28.],
        [48., 54., 49., 57., 50.]])

In [7]:
torch.amax(tensor, 2)

tensor([[56., 42., 44., 53.],
        [58., 52., 39., 59.],
        [54., 50., 55., 57.]])

In [6]:
a = torch.FloatTensor(1).uniform_(0, 2**32)
b = torch.FloatTensor(1).uniform_(0, 2**32)
a, b

(tensor([2.7132e+09]), tensor([2.8212e+09]))

In [7]:
# 原始的分类变量
categories = ['红色', '蓝色', '绿色', '红色', '绿色']

# 创建一个张量表示分类变量
tensor = torch.tensor([categories.index(category) for category in categories])

# 进行One-hot编码
one_hot = torch.nn.functional.one_hot(tensor)

print(tensor)
print(one_hot)

tensor([0, 1, 2, 0, 2])
tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [1, 0, 0],
        [0, 0, 1]])


In [9]:
c = [categories.index(category) for category in categories]
c

[0, 1, 2, 0, 2]

AttributeError: 'list' object has no attribute 'indexs'